### ISSUE TITLE
error message from docker container itself: Error in the push function.

### ISSUE THREAD

**Issue by JLarky** [sendgridlabs/loggly-docker#21]
I'm getting errors that are internal for syslog. Here's the error:

```
severity: Error
timestamp: 2016-03-07T17:57:59.638236+00:00
facility: messages generated internally by syslogd
priority: 43
host: 17010d56a5f9
unparsed:
message: unexpected GnuTLS error -53 in nsd_gtls.c:1618: Error in the push function. [v8.9.0 try http://www.rsyslog.com/e/2078 ]

```
![image 2016-03-07 10-22-54](https://cloud.githubusercontent.com/assets/7026/13580238/2be027b4-e456-11e5-8519-3981b74ff9d2.png)

I use docker like that (docker-compose format):
```
loggly-docker:
  restart: always
  image: sendgridlabs/loggly-docker
  ports:
   - 514/udp
  environment:
   - TAG=MyTag
   - TOKEN=xxxx
```
it also sends some other non application specific messages like:
```
action 'action 1' resumed (module 'builtin:omfwd') [v8.9.0 try http://www.rsyslog.com/e/2359 ]
-- MARK --
```
but I'm ok with those since at least they don't say "error" in them :)
